name: Ejecutar Verificador de Cursos oficial

on:
  schedule:
    # Ejecutar cada día a las 9:00 AM UTC (ajusta según tu zona horaria)
   # TEMPORAL - Cada 5 minutos para pruebas
    - cron: '*/5 * * * *'
    # Para ejecutar cada 2 días, descomenta la siguiente línea y comenta la de arriba
   - cron: '0 3 */2 * *' 
  
  # Permitir ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  verificar-cursos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Ajusta según la versión que uses
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar verificador de cursos
      env:
        # Variables de entorno - configúralas en GitHub Secrets
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        # Agrega todas las variables que use tu verificador_cursos.py
        # HOSTINGER_DB_HOST: ${{ secrets.HOSTINGER_DB_HOST }}
        # HOSTINGER_DB_USER: ${{ secrets.HOSTINGER_DB_USER }}
        # HOSTINGER_DB_PASS: ${{ secrets.HOSTINGER_DB_PASS }}
        # HOSTINGER_DB_NAME: ${{ secrets.HOSTINGER_DB_NAME }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python data/verificador_cursos.py
    
    - name: Notificar resultado
      if: success()
      run: echo "✅ Verificador de cursos ejecutado exitosamente $(date)"
    
    - name: Notificar error
      if: failure()
      run: echo "❌ Error al ejecutar verificador de cursos $(date)"
