name: Ejecutar Scraper y Verificador de Cursos

on:
  schedule:
   - cron: '0 3 */2 * *'  # Cada 2 días a las 9:00 PM México (3:00 AM UTC)
  
  # Permitir ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  scraper-y-verificador:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 1️⃣ Ejecutar scraper de Discudemy
      env:
        # Variables de base de datos (usando tus nombres exactos)
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
        # Variables de Telegram y admin
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        # Python path
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "🔍 Iniciando scraper de Discudemy..."
        echo "🔗 Conectando a: $DB_HOST"
        echo "👤 Usuario: $DB_USER"
        echo "🗄️ Base de datos: $DB_NAME"
        python data/scraper_discudemy.py
        echo "✅ Scraper de Discudemy completado"
    
    - name: 2️⃣ Ejecutar verificador de cursos
      env:
        # Variables de base de datos
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
        # Variables de Telegram y admin
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        # Python path
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "🔍 Iniciando verificador de cursos..."
        echo "🔗 Conectando a: $DB_HOST"
        python data/verificador_cursos.py
        echo "✅ Verificador de cursos completado"
    
    - name: ✅ Proceso completado exitosamente
      if: success()
      run: |
        echo "🎉 Ambos scripts ejecutados exitosamente"
        echo "⏰ Fecha y hora: $(date)"
        echo "📊 Scraper Discudemy ✅"
        echo "🔍 Verificador de cursos ✅"
    
    - name: ❌ Error en el proceso
      if: failure()
      run: |
        echo "💥 Error durante la ejecución"
        echo "⏰ Fecha y hora: $(date)"
        echo "ℹ️ Revisa los logs anteriores para más detalles"
