name: Ejecutar Verificador de Cursos

on:
  schedule:
    # Ejecutar cada día a las 9:00 AM UTC (ajusta según tu zona horaria)
    - cron: '0 9 * * *'
    # Ejecutar cada 2 días a las 9:00 AM UTC
    # - cron: '0 9 */2 * *'
  
  # Permitir ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  verificar-cursos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Ajusta según tu versión de Python
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Ejecutar verificador de cursos
      env:
        # Aquí defines las variables de entorno que necesita tu script
        # Estas las configurarás en GitHub Secrets
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        # Agrega todas las variables que necesites
        # HOSTINGER_DB_HOST: ${{ secrets.HOSTINGER_DB_HOST }}
        # HOSTINGER_DB_USER: ${{ secrets.HOSTINGER_DB_USER }}
        # HOSTINGER_DB_PASS: ${{ secrets.HOSTINGER_DB_PASS }}
        # HOSTINGER_DB_NAME: ${{ secrets.HOSTINGER_DB_NAME }}
      run: |
        cd data
        python verificador_cursos.py
    
    # Opcional: Notificar resultado
    - name: Notificar éxito
      if: success()
      run: echo "✅ Verificador de cursos ejecutado exitosamente"
    
    - name: Notificar error
      if: failure()
      run: echo "❌ Error al ejecutar verificador de cursos"
